In [1]:
import numpy as np

# Initialize weights, biases, and activations
weights = np.array([1.62, -0.61, -0.53, -1.07, 0.87, -2.30, 1.74, -0.76, 0.32, -0.25, 1.46, -2.06, -0.32, -0.38, 1.13,
                    -1.10, -0.17, -0.88, 0.04, 0.58, -1.10, 1.14, 0.90, 0.50, 0.90, -0.68, -0.12, -0.94, -0.27, 0.53,
                    -0.69, -0.40, -0.69, -0.85, -0.67, -0.01, -1.12, 0.23, 1.66, 0.74, -0.19, -0.89, -0.75, 1.69, 0.05,
                    -0.64, 0.19, 2.10, 0.12, 0.62, 0.30, -0.35, -1.14, -0.35, -0.21, 0.59, 0.84, 0.93, 0.29, 0.89, -0.75,
                    1.25, 0.51, -0.30, 0.49, -0.08, 1.13, 1.52, 2.19, -1.40, -1.44, -0.50, 0.16, 0.88, 0.32, -2.02])
biases = np.array([-0.31, 0.83, 0.23, 0.76, -0.22, -0.20, 0.19, 0.41, 0.20, 0.12, -0.67])

# Activations of the input layer (first layer)
activations = np.zeros(19)
activations[:8] = np.array([0.038, 0.12, 1.13, 1.20, 0.19, -0.38, -0.64, 0.42])

# Reshape activations, weights, and biases for each layer
activations = [
    activations[:8].reshape(-1, 1),  # Input layer activations (8 nodes)
    activations[8:14].reshape(-1, 1),  # Second layer activations (6 nodes)
    activations[14:18].reshape(-1, 1),  # Third layer activations (4 nodes)
    activations[18:].reshape(-1, 1)  # Output layer activations (1 node)
]
  
# Split weights and biases for each layer
weights = [
    weights[:48].reshape(6, 8),  # Weights between layer 1 and 2 (6x8 matrix)
    weights[48:72].reshape(4, 6),  # Weights between layer 2 and 3 (4x6 matrix)
    weights[72:].reshape(1, 4)  # Weights between layer 3 and 4 (1x4 matrix)
]

biases = [
    biases[:6].reshape(-1, 1),  # Biases for layer 2 (6 nodes)
    biases[6:10].reshape(-1, 1),  # Biases for layer 3 (4 nodes)
    biases[10:].reshape(-1, 1)  # Biases for layer 4 (1 node)
]

# Sigmoid activation function
def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))

# Feedforward process
z_values = []  # Store Z values (weighted sums before activation)
for layer_index in range(3):
    z = np.dot(weights[layer_index], activations[layer_index]) + biases[layer_index]  # Weighted sum
    z_values.append(z)
    activations[layer_index + 1] += sigmoid(z)  # Apply activation function to get new activations

# Output Z values for each layer
print("Z Values: ")
for layer_index in range(3):
    print(z_values[layer_index])

# Output activations for each layer after the feedforward process
print("Activations: ")
for layer_index in range(1, 4):
    print(activations[layer_index])

Z Values: 
[[-2.59804]
 [-1.11164]
 [-0.14906]
 [-0.5301 ]
 [-2.16912]
 [ 1.87958]]
[[-0.05959249]
 [ 2.07670495]
 [ 0.56323837]
 [ 0.48795276]]
[[-0.85813494]]
Activations: 
[[0.06926467]
 [0.24756527]
 [0.46280385]
 [0.37049356]
 [0.102558  ]
 [0.86756288]]
[[0.48510628]
 [0.88861832]
 [0.6372015 ]
 [0.61962404]]
[[0.29772916]]
